name: ngBump-when-detected

on:
  pull_request:
    branches: [ master ]

jobs:
  env:
    BUMP_NG: false
  
  set-BUMP_NG-if-update-required:
    name: set env.BUMP_NG if update required
    runs-on: ubuntu-latest

    steps:
    # - name: print GitHub context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   run: |
    #     echo "$GITHUB_CONTEXT"
    #     echo ${{ github.event.pull_request.title }}

    - uses: actions/checkout@v2

    - name: install dependencies
      run: npm install
    
    - name: create new PR when existing dependabot PR detected
      run: npm run bump-ng-libraries-package-json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    # - uses: actions/checkout@v2
    #   with:
    #     ref: master

