name: ngBump-when-detected

on:
  pull_request:
    branches: [ master ]

jobs:
  
  github-context:
    name: bump angular version if detected
    runs-on: ubuntu-latest

    steps:
    - name: print GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo ${{ github.event.pull_request.title }}
    
    - uses: actions/checkout@v2

    - name: install dependencies
      run: npm install    
    
    - name: create new PR when existing dependabot PR detected
      run: npm run bump-ng-libraries-package-json '${{ github.event.pull_request.title}}'

