name: ngBump-when-detected

on:
  pull_request:
    branches: [ master ]

env:
  BUMP_NG: false
  EXISTING_PR_FOR_BUMP_NG: false
  CURRENT_NG_VER: '-'
  NEW_NG_VER: '-'

jobs:
     
  create-new-BUMP_NG-if-update-required:
    name: create-new-BUMP_NG-if-update-required
    runs-on: ubuntu-latest

    steps:
    # - name: print GitHub context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   run: |
    #     echo "$GITHUB_CONTEXT"
    #     echo ${{ github.event.pull_request.title }}

    - uses: actions/checkout@v2

    - name: install dependencies
      run: npm install

    - name: get list of pending PRs and search for a dependabot PR which will bump angular version
      run: npm run is-ng-bump-required
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2
      if: ${{ !env.EXISTING_PR_FOR_BUMP_NG && env.BUMP_NG }}
      with:
        ref: master
        path: master-src
    - run: ls && cat package.json && cat master-src\package.json
        
    - name: create new PR when existing dependabot PR detected
      if: ${{ !env.EXISTING_PR_FOR_BUMP_NG && env.BUMP_NG }}
      run: cd master-src && node bump-ng-and-create-PR.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   

