name: ngBump-when-detected

on:
  pull_request:
    branches: [ master ]

jobs:
     
  create-new-BUMP_NG-if-update-required:
    name: create-new-BUMP_NG-if-update-required
    runs-on: ubuntu-latest
    # env:
    #   BUMP_NG: false
    #   EXISTING_PR_FOR_BUMP_NG: false
    #   CURRENT_NG_VER: '-'
    #   NEW_NG_VER: '-'

    steps:
    # - name: print GitHub context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   run: |
    #     echo "$GITHUB_CONTEXT"
    #     echo ${{ github.event.pull_request.title }}

    # share the variables with steps below
    - name: Set vars
      run: |
        export BUMP_NG=false
        echo "::set-env name=BUMP_NG::$BUMP_NG"
        export EXISTING_PR_FOR_BUMP_NG=false
        echo "::set-env name=EXISTING_PR_FOR_BUMP_NG::$EXISTING_PR_FOR_BUMP_NG"
        export CURRENT_NG_VER='-'
        echo "::set-env name=CURRENT_NG_VER::$CURRENT_NG_VER"
        export NEW_NG_VER='-'
        echo "::set-env name=NEW_NG_VER::$NEW_NG_VER"

    - uses: actions/checkout@v2

    - name: install dependencies
      run: npm install

    - name: get list of pending PRs and search for a dependabot PR which will bump angular version
      run: npm run is-ng-bump-required 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: print EXISTING_PR_FOR_BUMP_NG    
      run: echo $EXISTING_PR_FOR_BUMP_NG
    
    # - name: print when EXISTING_PR_FOR_BUMP_NG=TRUE
    #   if: ${{env.EXISTING_PR_FOR_BUMP_NG == 'true'}}
    #   run: echo 'print EXISTING_PR_FOR_BUMP_NG true!'

    # - name: print when EXISTING_PR_FOR_BUMP_NG=false
    #   if: ${{env.EXISTING_PR_FOR_BUMP_NG == 'false'}}
    #   run: echo 'print EXISTING_PR_FOR_BUMP_NG false!'

    #- name: create new PR when existing dependabot PR detected        
    #  if: env.EXISTING_PR_FOR_BUMP_NG && env.BUMP_NG 
    #  run: echo This works!

    - uses: actions/checkout@v2
      if: ${{env.EXISTING_PR_FOR_BUMP_NG == 'false' && env.BUMP_NG == 'true' }}
      with:
        ref: master
        path: master-src
   
    # - run: ls && cat package.json && cat master-src\package.json
        
    # - name: create new PR when existing dependabot PR detected
    #   if: ${{ !env.EXISTING_PR_FOR_BUMP_NG && env.BUMP_NG }}
    #   run: cd master-src && node bump-ng-and-create-PR.js
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   

